### ISSUE TITLE
Error: Unknown handler: directory

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#22]
We are using Hapi.js as our static server using the `directory` handler:
https://github.com/dwyl/learn-tdd/blob/5b132bfe5e1787b684ff44eadaf8b53438449323/static-server.js#L3

but when we attempt to upgrade to hapi `v9.x` we get:

```sh
Error: Unknown handler: directory
```

<img width="783" alt="hapi-stack-trace" src="https://cloud.githubusercontent.com/assets/194400/9285163/d4d34950-42da-11e5-80ee-e2ea4add9887.png">

full stack trace:
```sh
/Users/n/code/learn-tdd/node_modules/hapi/node_modules/hoek/lib/index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Unknown handler: directory
    at Object.exports.assert (/Users/n/code/learn-tdd/node_modules/hapi/node_modules/hoek/lib/index.js:723:11)
    at Object.exports.defaults (/Users/n/code/learn-tdd/node_modules/hapi/lib/handler.js:105:14)
    at new module.exports.internals.Route (/Users/n/code/learn-tdd/node_modules/hapi/lib/route.js:48:35)
    at internals.Connection._addRoute (/Users/n/code/learn-tdd/node_modules/hapi/lib/connection.js:359:17)
    at internals.Connection._route (/Users/n/code/learn-tdd/node_modules/hapi/lib/connection.js:351:18)
    at internals.Plugin._apply (/Users/n/code/learn-tdd/node_modules/hapi/lib/plugin.js:497:14)
    at internals.Plugin.route (/Users/n/code/learn-tdd/node_modules/hapi/lib/plugin.js:470:10)
    at Object.<anonymous> (/Users/n/code/learn-tdd/static-server.js:3:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
13 Aug 19:11:49 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nelsonic** [comment]
Apparently we need to *manually* register the plugin in order to serve a directory now...
https://github.com/hapijs/hapi/issues/2682#issuecomment-130574238 #lame :confused:

**Comment by barbalex** [comment]
:-(

**Comment by nelsonic** [comment]
What's making you *sad* @baralex ?
*How* can we help? :rainbow:

**Comment by barbalex** [comment]
sorry for bugging, I added inert and the plugin call
thanks for a great tool

**Comment by nelsonic** [comment]
@barbalex you are not "bugging" at all. 
glad you like the tool(s). 
Welcome to [**dwyl**](https://github.com/dwyl)! :-)

**Comment by barbalex** [comment]
:-)


2015-09-16 15:05 GMT+02:00 Nelson <notifications@github.com>:

**Comment by msmichellegar** [comment]
Just got this error and DWYL was the #1 result in my google search @nelsonic ;) :100:

**Comment by nelsonic** [comment]
Gotta love SEO for random github issues. :wink:
Glad you've got it working.
